### ISSUE TITLE
Counter object issue

### ISSUE THREAD

**Issue by rowanhere** [fum-is-chum/spam-bot#2]
getting error on new package , old one works good with mnemonic pharse 

`{}
Error: Failed to get counter object
undefined`

**Comment by fum-is-chum** [comment]
Are you using mnemonic or secretKey? you can only use 1 at a time on the code. If you use mnemonic, comment the secret key on line 421 and vice versa

**Comment by rowanhere** [comment]
well i have set my .env like this

`MNEMONICS=
SECRET_KEY=suiprivkey*********************
BATCH_SIZE=1
ITER=100
INTERVAL=`

The secret key is from spam website that it automatically generates but still gettin error 

`Batch Size: 1
--------------------------------------------------------------------------------
Running with 1 accounts
{}
Error: Failed to get counter object
undefined`

**Comment by fum-is-chum** [comment]
I've updated the code to better handle this case, please try again

**Comment by rowanhere** [comment]
sure lemme

**Comment by rowanhere** [comment]
have u used ys using private key to mine? try once plz

**Comment by fum-is-chum** [comment]
Yes, I did. Using private key only can only mine with 1 account at once. Are you facing any issues?

**Comment by fum-is-chum** [comment]
Just out of curiosity, have you supply at least a few SUI to your mining account?

**Comment by fum-is-chum** [comment]
- Please make sure you've installed the all the latest package by running `pnpm install`
- Make sure your wallet has SUI 

If none above solve your issue, please share screenshot of the terminal when you run the script
